#! /bin/bash
# Usage: ./script.sh -b

test_file_eos=/store/user/jferrant/siggen_Phi_omega/run_01_2022Feb12/miniaod/PHI_125_RUN_unweighted_events_Phi_125_omega_0p3/miniAOD_99.root
test_file_local=/uscms/home/bchiari1/nobackup/rootfiles/framework_unittest/miniAOD_99.root

UnitTest()
{
  printf "\n--- Test 1 ---\n\n"
  ./condor_submit.py $test_file_local --input_local /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc --twoprongSB full -t -f --mc
  printf "\n--- Test 2 ---\n\n"
  ./condor_submit.py $test_file_eos /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f --mc
  printf "\n--- Test 3 ---\n\n"
  ./condor_submit.py /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM --files 5 /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f --mc
  printf "\n--- Test 4 ---\n\n"
  ./condor_submit.py /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM --files 5 /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f --useLFN --selection muon --mc
}
Rebuild()
{
  echo "Got -b option: Rebuild"
  ./helper/prebuild_setup.sh
  UnitTest
}
NoRebuild()
{
  UnitTest
}

while getopts ":b" option; do
   case $option in
      b) # Rebuild scratch area
         Rebuild
         rm -rf TestJob_unit_test_cmslpc
         exit;;
   esac
done
NoRebuild
rm -rf TestJob_unit_test_cmslpc/
