#! /bin/bash
# Usage: ./script.sh -b

# 3 minute real submit test
# $ python condor_submit.py /uscms/home/bchiari1/nobackup/rootfiles/sigGenCondorFramework/UL18_miniaodv2/dy_numEvent100.root /store/user/bchiari1/unit_tests/

test_file_eos=/store/user/lpcrutgers/sthayil/pseudoaxions/ttPhiPS_M-1000/miniAOD_33.root
test_file_local=/uscms/home/bchiari1/nobackup/rootfiles/sigGenCondorFramework/UL18_miniaodv2/dy_numEvent100.root

UnitTest()
{
  printf "\n--- Test 1 ---\n\n"
  python condor_submit.py $test_file_local --input_local /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f
  printf "\n--- Test 2 ---\n\n"
  python condor_submit.py $test_file_eos /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f
  printf "\n--- Test 3 ---\n\n"
  python condor_submit.py /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM --files 5 /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f
  printf "\n--- Test 4 ---\n\n"
  python condor_submit.py /DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM --files 5 /store/user/bchiari1/unit_tests/ -d unit_test_cmslpc -t -f --useLFN
}
Rebuild()
{
  echo "Got -b option: Rebuild"
  ./for_submit/cmssw_src_setup.sh
  UnitTest
}
NoRebuild()
{
  UnitTest
}

while getopts ":b" option; do
   case $option in
      b) # Rebuild scratch area
         Rebuild
         exit;;
   esac
done
NoRebuild
rm -rf TestJob_unit_test_cmslpc
